SET search_path TO config, tmdata, bmdata, contacts, public;
\copy countries (code, name, creuser, lmuser) from '/projects/steady_v1.0/resources/example_data/countries.csv' DELIMITER ',' NULL as '' CSV;
\copy currencies (code, name,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/currencies.csv' DELIMITER ',' NULL as '' CSV;
\copy clients (name, country_id,language,currency_id,timezone,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/clients.csv' CSV;
\copy contacts (clients_id, note,customerid,supplierid,cidatsupplier,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/contacts.csv' DELIMITER ',' NULL as '' CSV;
\copy addresses (clients_id, type,addr_additional,street_postbox,postalcode,city,country_id,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/addresses.csv' DELIMITER ',' NULL as '' CSV;
\copy callnumbers (clients_id, type,number,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/callnumbers.csv' DELIMITER ',' NULL as '' CSV;
\copy emails (clients_id, type,email,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/emails.csv' DELIMITER ',' NULL as '' CSV;
\copy webaddresses (clients_id, type,webaddress,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/webaddresses.csv' DELIMITER ',' NULL as '' CSV;
\copy bankaccounts (clients_id, iban,bic,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/bankaccounts.csv' DELIMITER ',' NULL as '' CSV;
\copy companies (clients_id, name,taxnumber,salestaxid,taxfree,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/companies.csv' DELIMITER ',' NULL as '' CSV;
\copy contactpersons (clients_id, title,firstname,lastname,callnumber,email,company_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/contactpersons.csv' DELIMITER ',' NULL as '' CSV;
\copy conditions (clients_id, discount,cop,cod,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/conditions.csv' DELIMITER ',' NULL as '' CSV;
\copy persons (clients_id, title,firstname,lastname,contact_id,creuser,lmuser) from '/projects/steady_v1.0/resources/example_data/persons.csv' DELIMITER ',' NULL as '' CSV;