-- Database initialization script
-- Author: Andre Hahn
-- Date: 08.12.2018

DROP DATABASE IF EXISTS steady_dev;
DROP USER IF EXISTS steady_user;

CREATE USER steady_user WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 1 PASSWORD 'start123';
CREATE DATABASE steady_dev WITH OWNER=steady_user CONNECTION LIMIT = 1;